Feature/18/add prometheus support
sakuli/sakuli-enterprise-forwarder pull request #35
Opened 2020-03-11 08:17 UTC by svettwer

2020-03-12 21:13 UTC, s1hofmann requested changes
A nice and clean implementation.
I added little remarks, but overall it looks solid 👍

2020-03-12 21:13 UTC, s1hofmann commented on packages/sakuli-forwarder-prometheus/src/prometheus-forwarder.class.ts
> +    }
I'm a bit confused by the name here. What exactly is a legacy teststep? Why do we check for this property?

Also, I'd expect return type `boolean` for `is...` kind of methods / functions, not `string | boolean`.

2020-03-12 21:13 UTC, s1hofmann commented on packages/sakuli-forwarder-prometheus/src/gauge.utils.ts
> +    return number.toString().padStart(3, '0');
`String.prototype.padStart` is part of `ES2017`. With current tsconfig settings, TypeScript complains about not knowing `padStart`, but I guess we can upgrade our tsconfig to ES2017. See https://node.green/#ES2017-features-String-padding-String-prototype-padStart

2020-03-12 21:13 UTC, s1hofmann commented on packages/sakuli-forwarder-prometheus/src/prometheus-forwarder.class.ts
> +                          testStepIndex: number) {
Ordering of parameters is a bit off here, step and case are interleaved.

2020-03-12 21:13 UTC, s1hofmann commented on packages/sakuli-forwarder-prometheus/src/gauge.utils.spec.ts
> +            id: "Case_Context_Mock",
Are the underscore here wanted?

2020-03-13 11:13 UTC, svettwer commented on packages/sakuli-forwarder-prometheus/src/gauge.utils.ts
> +    return number.toString().padStart(3, '0');
I haven't recognized any complains from typescript. Strange... :thinking: 
Anyways, I'v double checked with Sakuli core. Sakuli core also uses ES2017 currently.

2020-03-13 11:13 UTC, svettwer commented on packages/sakuli-forwarder-prometheus/src/prometheus-forwarder.class.ts
> +    }
Done! Nice catch! :tada:

2020-03-13 11:16 UTC, svettwer commented on packages/sakuli-forwarder-prometheus/src/prometheus-forwarder.class.ts
> +                          testStepIndex: number) {
Thx! :+1:

2020-03-13 11:17 UTC, svettwer commented on packages/sakuli-forwarder-prometheus/src/gauge.utils.spec.ts
> +            id: "Case_Context_Mock",
Yep, wanted to add a little bit variation to test data there. ;-)

2020-03-13 12:42 UTC, s1hofmann approved these changes

2020-03-16 14:38 UTC, merged