Feature/52/gearman forwarder validation
sakuli/sakuli-enterprise-forwarder pull request #57
Opened 2020-07-02 10:54 UTC by MarleneSahra

2020-07-03 07:45 UTC, s1hofmann requested changes
Awesome work 👍 

There's just one thing with a test I'd like to discuss

2020-07-03 07:45 UTC, s1hofmann commented on packages/sakuli-forwarder-gearman/src/gearman-forwarder.class.spec.ts
> +    expect(gearmanForwarder.setup(project,logger)).rejects.toThrow();
Does this test really validate its assumption?

2020-07-03 14:20 UTC, MarleneSahra commented on packages/sakuli-forwarder-gearman/src/gearman-forwarder.class.spec.ts
> +    expect(gearmanForwarder.setup(project,logger)).rejects.toThrow();
resolved

2020-07-06 08:17 UTC, s1hofmann approved these changes

2020-07-06 11:40 UTC, merged