(#26) fixed gearman log output for errors
sakuli/sakuli-enterprise-forwarder pull request #87
Opened 2020-12-01 09:44 UTC by cliffle

2020-12-02 09:22 UTC, svettwer requested changes
Looks like a minimal change. :+1: 
Nevertheless, a test case would be great. Without a developer test (setting up sakuli, etc) I'm unable to see whether the change fixes the issue.

2020-12-03 11:31 UTC, svettwer requested changes
Thx for adding the test.

While reviewing the change from E2E, I recognized that the errors are printed to debug level, even if all of them are errors causing a promise rejection. Therefore I suggested to change the log level. It's a bit off topic but changing it now would be more efficient than raising another ticket. Or do you see any reason why we should keep it on debug?

Sample log
```
[Thu Dec 03 2020 12:23:42 GMT+0100 (GMT+01:00)] DEBUG: Received Gearman event error with following data:
Error: connect ECONNREFUSED 127.0.0.1:4730
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  [stack]: 'Error: connect ECONNREFUSED 127.0.0.1:4730\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)',
  [message]: 'connect ECONNREFUSED 127.0.0.1:4730',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4730
}
[Thu Dec 03 2020 12:23:42 GMT+0100 (GMT+01:00)] ERROR: Failed to forward, error occured.
```

2020-12-03 11:31 UTC, svettwer commented on packages/sakuli-forwarder-gearman/src/gearman/submit-job.function.spec.ts
> +    expect(logger.debug).toHaveBeenCalledWith(`Received Gearman event ${event} with following data:`, argsObject);
```suggestion
    expect(logger.error).toHaveBeenCalledWith(`Received Gearman event ${event} with following data:`, argsObject);
```

2020-12-03 11:31 UTC, svettwer commented on packages/sakuli-forwarder-gearman/src/gearman/submit-job.function.ts
> +                log.debug(`Received Gearman event ${evt} with following data:`, args);
```suggestion
                log.error(`Received Gearman event ${evt} with following data:`, args);
```

2020-12-03 11:45 UTC, cliffle commented
Totally agree with you that it should be logged on error level. I didn't even notice that :+1:

2020-12-03 11:50 UTC, svettwer submitted a review, later dismissed

2020-12-03 12:02 UTC, svettwer approved these changes

2020-12-03 12:43 UTC, merged